### ISSUE TITLE
QHttpHeader Issue

### ISSUE THREAD

**Issue by surfhai** [wiedi/libmaia#12]
The server didn't work until I checked the MaiaXmlRpcServerConnection::readFromSocket() method. It gave me the following output:

    headerString: "POST /RPC2 HTTP/1.1\r\n"
    headerString: "User-Agent: XMLRPC++ 0.7\r\n"
    headerString: "Host: 192.168.2.101:8888\r\n"
    headerString: "Content-Type: text/xml\r\n"
    headerString: "Content-length: 1252\r\n"

but statet that the header->contentLength() == 0 so that nothing happens. As you can see the contentLength isn't 0 I removed the following return statement for that check.

    void MaiaXmlRpcServerConnection::readFromSocket() {
        QString lastLine;
    
    	while(clientConnection->canReadLine() && !header) {
    		lastLine = clientConnection->readLine();
    		headerString += lastLine;
    		if(lastLine == "\r\n") { /* http header end */
    			header = new QHttpRequestHeader(headerString);
    			if(!header->isValid()) {
    				/* return http error */
    				qDebug() << "Invalid Header";
    				return;
    			} else if(header->method() != "POST") {
    				/* return http error */
    				qDebug() << "No Post!";
    				return;
    			} else if(!header->contentLength()) {
    				/* return fault */
                    qDebug() << "No Content Length (maybe a bug in QtHttpHeader)";
                    //return;
    			}
    		}
    	}
    	if(header) {
            if(header->contentLength() <= clientConnection->bytesAvailable()) {
    			/* all data complete */
    			parseCall(clientConnection->readAll());
    		}
        }
    }

**Comment by wiedi** [comment]
thanks for the report.
@carlos22 removed the check in e35c51bce24daf4379605a4978c5453b52959bcb which was probably not needed in most cases anyway.
