### ISSUE TITLE
Usage Questions

### ISSUE THREAD

**Issue by msmith626** [wiedi/libmaia#8]
Hi,

First, please forgive my misuse of the issues function on GitHub, but I didn't see any other support/QA communication methods. Secondly, great project!

I have a couple questions, and I am a mostly novice developer:
1) When using libmaia, I'd like to make multiple RPC's to different hosts (XML-RPC service instances that reside on disjoint servers) and utilize the same RPC response/fault handler methods. Is it possible to discover what host (URL) the RPC is from when in one of the "RPC handling" methods? Due to the default asynchronous nature of Qt's signals/slots, if I make several RPC's they don't necessarily arrive in the order they were called, correct? I could obviously modify libmaia and add support for this to work for my application, but I wanted to find out if there was something obvious that I was missing first.

2) Any thoughts on handling timeouts (eg, too long of a running RPC on the server side, or something stuck, or the XML-RPC server instance died/crashed)? Or what about performing an RPC from a client to a web server that isn't actually an XML-RPC server and doesn't respond? I haven't read up on how XML-RPC works itself, and if there is some type of handshake first, or just send from the client to the server and wait for a response. So maybe both causes of timeouts described behave the same.

Thanks for your time.

--Marc

**Comment by wiedi** [comment]
Hi,

sorry for the late response.
1.) It is possible, I just don't recall how I did that in the past. I think I had to do my own mapping.
2.) It just uses QNetworkRequest internally. So what usually is done is implement your timeout handler that does disconnects the signals and does cleanup and error handling
